from . import hr_dependents_information
from . import hr_employee
from . import hr_employee_public
from . import hr_employee_working
from . import hr_health_insurance_history
from . import hr_health_insurance_gap
from . import hr_labor_harm_insurance_gap
from . import hr_labor_harm_insurance_history
from . import hr_labor_insurance_gap
from . import hr_labor_insurance_history
from . import hr_batch_operation
from . import res_users
from . import hr_department
from . import sl_res_company
from . import sl_res_partner
from . import sl_plant_area
from . import hr_health_report_line
from . import sl_health_report_check_setting
from . import sl_license_check_setting
from . import sl_license_line
from . import hr_labor_pension_gap
from . import hr_labor_pension_history
from . import hr_insurance_doc
from . import hr_salary_tax_gap
from . import sl_res_bank
