from . import hr_payroll_structure
from . import hr_salary_rule
from . import hr_salary_rule_category
from . import hr_employee
from . import hr_payslip
from . import hr_payslip_extend
from . import hr_payslip_computed
from . import hr_payslip_set
from . import hr_payslip_line
from . import starrylord_payslip_holiday_middleware
from . import starrylord_payslip_overtime_middleware
from . import starrylord_payslip_overtime_holiday_middleware
from . import starrylord_employee_payslip_setting
from . import starrylord_employee_payslip_salary_setting
from . import hr_payslip_sheet
from . import res_config_settings
from . import starrylord_holiday_used_record
from . import sl_bonus_record
from . import sl_payroll_adjustment
from . import hr_payslip_other_line
from . import payslip_withholding_statement_sheet
