{
    'name': "Starry Lord HRM 加班",
    'summary': "Starry Lord HRM",
    'description': "Starry Lord HRM 加班",
    'author': "Starry Lord",
    'website': "https://www.starrylord.com.tw",
    'category': 'HRM',
    'version': '19.0.0.1',
    'depends': ['base', 'hr', 'sl_tier_validation', 'sl_hrm_holiday', 'sl_hr_attendance'],
    'data': [
        'security/starrylord_overtime_security.xml',
        'security/ir.model.access.csv',
        'security/sl_hrm_overtime_security.xml',
        'views/starrylord_overtime_apply.xml',
        'views/starrylord_overtime_settings.xml',
        'views/starrylord_overtime_type.xml',
        'views/starrylord_holiday_allocation_view.xml',
        'wizard/overtime_apply_record_wizard_form.xml',
        'data/starrylord_overtime_data.xml',
        'views/overtime_exchange_consent_views.xml',
        'report/overtime_exchange_consent_templates.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
